# config/atm8.yaml
title: "2D Turbulence"
source: "pyqg.BTModel"

architecture:
  n_threads: 1

grid:
  n_grid: 256

model:
  rek: 1.0e-3
  cnu: 0.2
  af: 1.0
  kf: 32.0
  dkf: 2.0
  beta: 5.0

simulation:
  dt: 0.01
  t_write: 1.0
  t_epoch: 100.0