# config/atm.yaml
title: "2D Turbulence"
source: "pyqg.BTModel"

architecture:
  n_threads: 1

grid:
  n_grid: 256

model:
  rek: 0.01
  cnu: 0.2
  af: 1.0
  kf: 16.0
  dkf: 2.0
  beta: 0.0

simulation:
  dt: 0.01
  t_write: 1.0
  t_epoch: 100.0